CREATE TABLE "TodoDB" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Title" varchar(50),
  "Description" varchar(500),
  "Created_at" timestamp,
  "Due_at" timestamp,
  "Status" bool
);
